
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace LGameFramework.GameCore.Config
{ 
    public enum InteractType
    {
        /// <summary>
        /// 对话
        /// </summary>
        Talk = 0,
        /// <summary>
        /// 举起
        /// </summary>
        CarryUp = 1,
        /// <summary>
        /// 拾取
        /// </summary>
        PickUp = 2,
        /// <summary>
        /// 推拉
        /// </summary>
        PushPull = 3,
    }

} 

