
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace LGameFramework.GameCore.Config
{ 
    public enum RoleCareer
    {
        Career1 = 0,
        Career2 = 1,
        Career3 = 2,
    }

} 

