
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LGameFramework.GameCore.Config
{
    public sealed partial class T_Interact : Luban.BeanBase
    {
        public T_Interact(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Type = (InteractType)_buf.ReadInt();
        }

        public static T_Interact DeserializeT_Interact(ByteBuf _buf)
        {
            return new T_Interact(_buf);
        }

        public readonly int Id;
        public readonly InteractType Type;
    
        public const int __ID__ = 1398295009;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "}";
        }
    }

}
