
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LGameFramework.GameCore.Config
{
    public sealed partial class T_Item : Luban.BeanBase
    {
        public T_Item(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            Level = _buf.ReadInt();
        }

        public static T_Item DeserializeT_Item(ByteBuf _buf)
        {
            return new T_Item(_buf);
        }

        /// <summary>
        /// id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;
    
        public const int __ID__ = -1800094658;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "name:" + Name + ","
            + "desc:" + Desc + ","
            + "level:" + Level + ","
            + "}";
        }
    }

}
