
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LGameFramework.GameCore.Config
{
    public sealed partial class T_Monster : Luban.BeanBase
    {
        public T_Monster(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BaseSkin = new System.Collections.Generic.Dictionary<int, string>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); string _v0;  _v0 = _buf.ReadString();     BaseSkin.Add(_k0, _v0);}}
            ControllerName = _buf.ReadString();
            InteractId = _buf.ReadInt();
        }

        public static T_Monster DeserializeT_Monster(ByteBuf _buf)
        {
            return new T_Monster(_buf);
        }

        public readonly int Id;
        public readonly System.Collections.Generic.Dictionary<int, string> BaseSkin;
        public readonly string ControllerName;
        public readonly int InteractId;
    
        public const int __ID__ = -537791793;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "BaseSkin:" + Luban.StringUtil.CollectionToString(BaseSkin) + ","
            + "ControllerName:" + ControllerName + ","
            + "InteractId:" + InteractId + ","
            + "}";
        }
    }

}
