
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LGameFramework.GameCore.Config
{
    public sealed partial class T_MonsterRefresh : Luban.BeanBase
    {
        public T_MonsterRefresh(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            MonsterId = _buf.ReadInt();
            HP = _buf.ReadInt();
            MP = _buf.ReadFloat();
            MoveSpeed = _buf.ReadFloat();
            RotationSpeed = _buf.ReadFloat();
        }

        public static T_MonsterRefresh DeserializeT_MonsterRefresh(ByteBuf _buf)
        {
            return new T_MonsterRefresh(_buf);
        }

        public readonly int Id;
        public readonly int MonsterId;
        public readonly int HP;
        public readonly float MP;
        public readonly float MoveSpeed;
        public readonly float RotationSpeed;
    
        public const int __ID__ = -27770612;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MonsterId:" + MonsterId + ","
            + "HP:" + HP + ","
            + "MP:" + MP + ","
            + "MoveSpeed:" + MoveSpeed + ","
            + "RotationSpeed:" + RotationSpeed + ","
            + "}";
        }
    }

}
