
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LGameFramework.GameCore.Config
{
    public sealed partial class T_Role : Luban.BeanBase
    {
        public T_Role(ByteBuf _buf) 
        {
            Career = (RoleCareer)_buf.ReadInt();
            Hp = _buf.ReadInt();
            Mp = _buf.ReadInt();
            MoveSpeed = _buf.ReadFloat();
            RotationSpeed = _buf.ReadFloat();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BaseSkin = new System.Collections.Generic.Dictionary<int, string>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); string _v0;  _v0 = _buf.ReadString();     BaseSkin.Add(_k0, _v0);}}
        }

        public static T_Role DeserializeT_Role(ByteBuf _buf)
        {
            return new T_Role(_buf);
        }

        public readonly RoleCareer Career;
        public readonly int Hp;
        public readonly int Mp;
        public readonly float MoveSpeed;
        public readonly float RotationSpeed;
        public readonly System.Collections.Generic.Dictionary<int, string> BaseSkin;
    
        public const int __ID__ = -1799831135;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Career:" + Career + ","
            + "Hp:" + Hp + ","
            + "Mp:" + Mp + ","
            + "MoveSpeed:" + MoveSpeed + ","
            + "RotationSpeed:" + RotationSpeed + ","
            + "BaseSkin:" + Luban.StringUtil.CollectionToString(BaseSkin) + ","
            + "}";
        }
    }

}
