
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace LGameFramework.GameCore.Config
{
    //废弃类 默认是预加载 改成惰性加载
    public partial class Tables
    {
        
    }

}
