
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LGameFramework.GameCore.Config
{
    public partial class TB_Monster : ITBConfig
    {
        private System.Collections.Generic.Dictionary<int, T_Monster> _dataMap;
        private System.Collections.Generic.List<T_Monster> _dataList;
        
        public void OnInit(ByteBuf _buf)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, T_Monster>();
            _dataList = new System.Collections.Generic.List<T_Monster>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                T_Monster _v;
                _v = T_Monster.DeserializeT_Monster(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
        }

        public System.Collections.Generic.Dictionary<int, T_Monster> DataMap => _dataMap;
        public System.Collections.Generic.List<T_Monster> DataList => _dataList;

        public T_Monster GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public T_Monster Get(int key) => _dataMap[key];
        public T_Monster this[int key] => _dataMap[key];

        public void ResolveRef(Tables tables)
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef(tables);
            }
        }

    }

}
