
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LGameFramework.GameCore.Config
{
    public partial class TB_Role : ITBConfig
    {
        private System.Collections.Generic.Dictionary<RoleCareer, T_Role> _dataMap;
        private System.Collections.Generic.List<T_Role> _dataList;
        
        public void OnInit(ByteBuf _buf)
        {
            _dataMap = new System.Collections.Generic.Dictionary<RoleCareer, T_Role>();
            _dataList = new System.Collections.Generic.List<T_Role>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                T_Role _v;
                _v = T_Role.DeserializeT_Role(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Career, _v);
            }
        }

        public System.Collections.Generic.Dictionary<RoleCareer, T_Role> DataMap => _dataMap;
        public System.Collections.Generic.List<T_Role> DataList => _dataList;

        public T_Role GetOrDefault(RoleCareer key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public T_Role Get(RoleCareer key) => _dataMap[key];
        public T_Role this[RoleCareer key] => _dataMap[key];

        public void ResolveRef(Tables tables)
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef(tables);
            }
        }

    }

}
